In [15]:
import numpy as np
import numpy.linalg as linalg

In [4]:
A = np.array([[2, -1.25],
[1.25, -1.625]])
A

array([[ 2.   , -1.25 ],
       [ 1.25 , -1.625]])

In [11]:
b = np.array([0, -0.75]).reshape((2,1))
b

array([[ 0.  ],
       [-0.75]])

In [20]:
x = linalg.solve(A,b)
x

array([[0.55555556],
       [0.88888889]])

In [17]:
linalg.det(A)

-1.6874999999999998

In [21]:
A.dot(x.T)

ValueError: shapes (2,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)